// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB88g3acvAMRcrdxLkprTBqRu9mkg5bLM8',
    appId: '1:107869049252:web:53c04ef41a7e434d7c3131',
    messagingSenderId: '107869049252',
    projectId: 'upirs-3c467',
    authDomain: 'upirs-3c467.firebaseapp.com',
    databaseURL: 'https://upirs-3c467-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'upirs-3c467.appspot.com',
    measurementId: 'G-JVKXBYM4MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlgeRdziIw--opjbxce9EV1aIFVCSazK8',
    appId: '1:107869049252:android:34b023b03934bea47c3131',
    messagingSenderId: '107869049252',
    projectId: 'upirs-3c467',
    databaseURL: 'https://upirs-3c467-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'upirs-3c467.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZjKxgtQM-IevyiYyqGeTVzYVjRqHpoCo',
    appId: '1:107869049252:ios:9f3d294d9d1af43b7c3131',
    messagingSenderId: '107869049252',
    projectId: 'upirs-3c467',
    databaseURL: 'https://upirs-3c467-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'upirs-3c467.appspot.com',
    iosBundleId: 'com.example.upmDrrmIrsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZjKxgtQM-IevyiYyqGeTVzYVjRqHpoCo',
    appId: '1:107869049252:ios:9f3d294d9d1af43b7c3131',
    messagingSenderId: '107869049252',
    projectId: 'upirs-3c467',
    databaseURL: 'https://upirs-3c467-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'upirs-3c467.appspot.com',
    iosBundleId: 'com.example.upmDrrmIrsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdTlYekhT-DRqGN5wrvb9t3EPf8eE_yWY',
    appId: '1:107869049252:web:23b736b9dbcd3d817c3131',
    messagingSenderId: '107869049252',
    projectId: 'upirs-3c467',
    authDomain: 'upirs-3c467.firebaseapp.com',
    databaseURL: 'https://upirs-3c467-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'upirs-3c467.appspot.com',
    measurementId: 'G-XBSFXQJ1EP',
  );
}
